version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  docker-build-and-deploy:
    docker:
      - image: "julien23/thalesdataproject:latest"
        auth:
          username: julien23
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
        docker_layer_caching: true

      # script
      - run: "docker build -t thalesdataproject:latest ."
      - run: "docker push julien23/thalesdataproject:latest"

workflows:
  test_and_build:
    jobs:
      - maven/test
      - build
